name: Shopee Auto Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9,12,15,18,21 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Garante que o robô possa gravar arquivos ✍️
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Run script
        env:
          SHOPEE_APP_ID: ${{ secrets.SHOPEE_APP_ID }}
          SHOPEE_APP_SECRET: ${{ secrets.SHOPEE_APP_SECRET }}
        run: python bot_shopee.py
        
      - name: Salvar links no repositório
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add links_do_dia.json
          git commit -m "Novos links encontrados" || echo "Sem mudanças"
          git push
