name: Shopee Auto Bot

on:
  schedule:
    # Executa às 09h, 12h, 15h, 18h e 21h (Horário de Brasília)
    - cron: '0 12,15,18,21,0 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    # ESSA LINHA É O SEGREDO: Dá permissão para o bot salvar o histórico e não repetir produtos
    permissions:
      contents: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar Robô
        env:
          SHOPEE_APP_ID: ${{ secrets.SHOPEE_APP_ID }}
          SHOPEE_APP_SECRET: ${{ secrets.SHOPEE_APP_SECRET }}
        run: python bot_shopee.py

      - name: Salvar Memória e Resultados
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "ShopeeBot"
          git add links_do_dia.json integracao_shopee.csv historico_completo.json
          git commit -m "Automação: Atualização das $(date +'%d/%m/%Y %H:%M')" || exit 0
          git push
